### ISSUE TITLE
IE8 'insecure content' warning

### ISSUE THREAD

**Issue by taylortom** [tomgreenfield/adapt-teleporter#1]
See `teleporter.hbs` ln 5

Need to remove the protocol from the image src, as brings up the 'insecure content' warning in IE8 if running course from a secure server.

**Comment by tomgreenfield** [comment]
The URL wasn't made protocol-less because the site hosting the asset does accept HTTPS connections. I will instead be including the asset in the extension itself, providing the grunt/gulp tasks allow for this.

**Comment by moloko** [comment]
in the interim, could you accept PR #2 just to fix for now?

Absolute URLs need to be protocol-less as you can't know in advance whether a course containing this extension will be loaded from http or https

**Comment by tomgreenfield** [comment]
This was fixed in https://github.com/tomgreenfield/adapt-teleporter/commit/a5f75989087ab79a8aca278809c1bd3dc26b274c as part of refactor. Gulp CLI pulls down the develop branch.

Now also patched master in https://github.com/tomgreenfield/adapt-teleporter/commit/89e971a1a0eba322c3b49ef377a2d5d8166ad7bf.
